import type { Component } from 'vue'
import {
  Star,
  Flame,
  Zap,
  Footprints,
  Music,
  PartyPopper,
  WandSparkles,
  Sparkles,
  Crown,
  Heart,
  StarHalf,
  Flag,
  Globe,
  Hand,
  Medal,
  ChartPie,
  CircleGauge,
  ChartBar,
  Trophy,
} from '@lucide/vue'

/** Maps AchievementDefinition.icon string keys (data/achievements.ts) to Lucide components. */
export const achievementIcons: Record<string, Component> = {
  star: Star,
  flame: Flame,
  zap: Zap,
  footprints: Footprints,
  music: Music,
  'party-popper': PartyPopper,
  'wand-sparkles': WandSparkles,
  sparkles: Sparkles,
  crown: Crown,
  heart: Heart,
  'star-half': StarHalf,
  flag: Flag,
  globe: Globe,
  hand: Hand,
  medal: Medal,
  'chart-pie': ChartPie,
  gauge: CircleGauge,
  'chart-bar': ChartBar,
  trophy: Trophy,
}
